# Generated by Django 6.0.4 on 2026-05-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('INFO', 'Información General'), ('APROBADO', 'Solicitud Aprobada'), ('Rechazado', 'Solicitud Rechazada'), ('ALERTA', 'Alerta / Vencimiento'), ('CARENT', 'Carnet de Usuario')], default='INFO', max_length=20),
        ),
    ]
