# Generated by Django 6.0.4 on 2026-05-10 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_alter_notificacion_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='fecha_aprobación',
            new_name='fecha_aprobacion',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='fecha_devolución_esperada',
            new_name='fecha_devolucion_esperada',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='fecha_devolución_real',
            new_name='fecha_devolucion_real',
        ),
    ]
