# Generated by Django 6.0.4 on 2026-05-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_rename_fecha_aprobación_prestamo_fecha_aprobacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='duracion_dias',
            field=models.IntegerField(choices=[(7, '7 días'), (15, '15 días')], default=7, help_text='Duración inicial del Préstamo'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('DEVUELTO', 'Devuelto'), ('VENCIDO', 'Vencido'), ('RENOVADO', 'Renovado'), ('RENOVACION_SOLICITADA', 'Renovacion Solicitada')], default='SOLICITADO', max_length=25),
        ),
    ]
