# Generated by Django 6.0.4 on 2026-05-27 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_prestamo_duracion_dias_alter_prestamo_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='observaciones_entrega',
        ),
    ]
