# Generated by Django 6.0.4 on 2026-05-05 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EXCEL_MENSUAL', 'Reporte Estadístico Mensual'), ('ASISTENCIA', 'Formato de Asistencia'), ('INVENTARIO', 'Reporte de Inventario')], max_length=50)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('archivo_respaldo', models.FileField(blank=True, null=True, upload_to='auditoria_reportes/')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
            ],
            options={
                'verbose_name': 'Registro de Reporte',
                'verbose_name_plural': 'Historial de Reportes Generados',
            },
        ),
    ]
