# Generated by Django 6.0.4 on 2026-06-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroreporte',
            name='archivo_respaldo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
