# Generated by Django 6.0.4 on 2026-06-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_alter_registroreporte_archivo_respaldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroreporte',
            name='tipo',
            field=models.CharField(choices=[('INVENTARIO', 'Reporte de Inventario'), ('PRESTAMOS', 'Reporte Mensual de Préstamos'), ('RENDIMIENTO', 'Reporte de Morosidad / Retrasos')], max_length=50),
        ),
    ]
