# Generated by Django 6.0.4 on 2026-04-24 22:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo_dewey', models.CharField(help_text='Ej: 800, Literatura', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estante', models.CharField(help_text='Ej: Referencias 1', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('cutter', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(verbose_name='Sinopsis')),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='libros/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('origen', models.CharField(choices=[('VNZ', 'Venezolana'), ('INT', 'Internacional'), ('UNI', 'Universal')], help_text='Necesario para el desglose de Novela, Poesía, etc.', max_length=3)),
                ('es_infantil', models.BooleanField(default=False, help_text='Marca esto para clasificarlo como cuentos (X)', verbose_name='¿Es cuento Infantil?')),
                ('es_bolivariano', models.BooleanField(default=False, help_text='Marca esto para clasificarlo en la sección bolivariana', verbose_name='¿Pertenece a la sección Bolivariana?')),
                ('autores', models.ManyToManyField(related_name='libros', to='catalogo.autor')),
                ('generos', models.ManyToManyField(related_name='libros', to='catalogo.genero')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_inventario', models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Código de Inventario')),
                ('anio_publicacion', models.IntegerField(verbose_name='Año de Publicación')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PRESTADO', 'Prestado'), ('DONADO', 'DONADO'), ('PERDIDO', 'Perdido')], default='DISPONIBLE', max_length=20)),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.editorial')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplares', to='catalogo.libro')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejemplares', to='catalogo.ubicacion')),
            ],
        ),
    ]
