# Generated by Django 6.0.4 on 2026-04-24 22:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula/DNI')),
                ('carnet', models.CharField(max_length=20, unique=True, verbose_name='Carnet')),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('USUARIO', 'Usuario')], default='USUARIO', max_length=10)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado'), ('PENDIENTE', 'Pendiente de Activación')], default='PENDIENTE', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Documento_Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CEDULA', 'Cedula de Identidad'), ('RIF', 'Registro de Información Fiscal'), ('REFERENCIAS', 'Referencia Personal'), ('FOTO_CARNET', 'Foto tipo Carnet'), ('OTRO', 'Otro Documento')], max_length=20)),
                ('archivo', models.FileField(help_text='Formatos permitidos: PDF, JPG, PNG', upload_to='documentos_usuarios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.perfil')),
            ],
            options={
                'verbose_name': 'Documento de Perfil',
                'verbose_name_plural': 'Documentos de Perfiles',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
