# Generated by Django 6.0.4 on 2026-05-12 04:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDigital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría Digital',
                'verbose_name_plural': 'Categorías Digitales',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDigital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo_pdf', models.FileField(upload_to='repositorio/pdfs/')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='repositorio/portadas/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('descargas', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='repositorio.categoriadigital')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
