# Generated by Django 6.0.4 on 2026-06-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentodigital',
            name='archivo_pdf',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='documentodigital',
            name='portada',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
